---

- name: TEMPLATE | Template out the required files
  become: true
  become_user: root
  template:
    src: 'j2.resolv.conf'
    dest: '/etc/resolv.conf'
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"
